blank_issues_enabled: false
contact_links:
  - name: ğŸ“„ Documentation amendment
    url: https://github.com/CommandAPI/docs/issues/new/choose
    about: Is there something wrong with the documentation? Raise it in our docs repository!
  - name: ğŸƒ Get quick support
    url: https://discord.com/invite/G4SzSxZ
    about: |
      The CommandAPI Discord is the primary place to go to get quick support for the CommandAPI.
      If you have a question or need help, drop by and we can work through your issue together!
